default: &default
 adapter: postgresql
 encoding: utf8
 pool: 5
 username: stockapp_development
 password: '@StockApp'
 host: localhost

development:
  <<: *default
  database: stockapp_development

test:
  <<: *default
  database: stockapp_test

production:
  <<: *default
  database: stockapp_production
  username: stockapp
  password: <%= ENV['STOCKAPP_DATABASE_PASSWORD'] %>
